name: Java CI with Gradle

on:
  push:
    paths:
      - "**.java"
      - "**.json"
      - "gradle**"
      - "*.gradle"
  pull_request:
    paths:
      - "**.java"
      - "**.json"
      - "gradle**"
      - "*.gradle"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "microsoft"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"

    - name: Compile Java code
      run: ./gradlew remapJar --stacktrace --warning-mode=fail

    - name: Validate JSON files
      run: ./gradlew spotlessJsonCheck || (echo "::error::JSON validation failed! Run './gradlew spotlessApply' to fix style issues, or check the full error message for syntax errors." && exit 1)

    - name: Validate Java code style
      run: ./gradlew spotlessCheck || (echo "::error::Java code style validation failed! To fix, run 'Clean Up' and then 'Format' in Eclipse, or './gradlew spotlessApply' in the terminal." && exit 1)

    - name: Run unit tests
      run: ./gradlew test --stacktrace --warning-mode=fail

    - name: Validate access widener
      run: ./gradlew validateAccessWidener --stacktrace --warning-mode=fail

    - name: Build
      run: ./gradlew build --stacktrace --warning-mode=fail

    - name: Upload to VirusTotal for analysis
      if: ${{ env.VIRUSTOTAL_API_KEY }}
      uses: crazy-max/ghaction-virustotal@v4
      with:
        vt_api_key: ${{ env.VIRUSTOTAL_API_KEY }}
        files: |
          ./build/libs/*.jar
      # An error in this step means that the upload failed, not that a false
      # positive was detected.
      continue-on-error: true

    - name: Run the mod and take screenshots
      uses: modmuss50/xvfb-action@c56c7da0c8fc9a7cb5df2e50dd2a43a80b64c5cb
      with:
        run: ./gradlew runEndToEndTest --stacktrace --warning-mode=fail

    - name: Upload test screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Test Screenshots
        path: run/screenshots
