name: "Close stale issues / pull requests"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: |
            This issue has been open for a while with no recent activity. If this issue is still important to you, please add a comment within the next 7 days to keep it open. Otherwise, the issue will be automatically closed to free up time for other tasks.
            
            Issues should be closed if:
            - They are duplicates of other issues
            - There is not enough demand
            - They are no longer relevant
            - There are not enough details
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: "status:stale"
          stale-pr-label: "status:stale"
